// Generated by scripts/migrate-wordpress.mjs
export const legacyRedirects = [
  {
    source: '/2024/05/11/post-19/',
    destination: '/news/post-19/',
  },
  {
    source: '/2024/05/12/post-54/',
    destination: '/news/post-54/',
  },
  {
    source: '/2024/05/12/post-63/',
    destination: '/news/post-63/',
  },
  {
    source: '/2024/06/07/post-116/',
    destination: '/news/post-116/',
  },
  {
    source: '/2024/07/11/post-135/',
    destination: '/news/post-135/',
  },
  {
    source: '/2024/07/20/post-148/',
    destination: '/news/post-148/',
  },
  {
    source: '/2024/08/06/post-177/',
    destination: '/news/post-177/',
  },
  {
    source: '/2024/08/07/planet-world/',
    destination: '/news/planet-world/',
  },
  {
    source: '/2024/08/09/post-185/',
    destination: '/news/post-185/',
  },
  {
    source: '/2024/08/17/post-200/',
    destination: '/news/post-200/',
  },
  {
    source: '/2024/09/02/post-213/',
    destination: '/news/post-213/',
  },
  {
    source: '/2024/09/23/all-dreambreak-remix-phase-1/',
    destination: '/news/all-dreambreak-remix-phase-1/',
  },
  {
    source: '/2024/10/04/post-268/',
    destination: '/news/post-268/',
  },
  {
    source: '/2024/10/19/forever-night/',
    destination: '/news/forever-night/',
  },
  {
    source: '/2024/11/30/post-318/',
    destination: '/news/post-318/',
  },
  {
    source: '/2025/01/01/post-326/',
    destination: '/news/post-326/',
  },
  {
    source: '/2025/03/23/post-1539/',
    destination: '/news/post-1539/',
  },
  {
    source: '/2025/04/04/post-1556/',
    destination: '/news/post-1556/',
  },
  {
    source: '/2025/04/28/future-magic/',
    destination: '/news/future-magic/',
  },
  {
    source: '/2025/05/04/post-1598/',
    destination: '/news/post-1598/',
  },
  {
    source: '/2025/05/14/post-1606/',
    destination: '/news/post-1606/',
  },
  {
    source: '/2025/06/29/post-1639/',
    destination: '/news/post-1639/',
  },
  {
    source: '/2025/07/06/post-1650/',
    destination: '/news/post-1650/',
  },
  {
    source: '/2025/07/06/post-1652/',
    destination: '/news/post-1652/',
  },
  {
    source: '/2025/07/27/post-1658/',
    destination: '/news/post-1658/',
  },
  {
    source: '/2025/08/10/the-dreamy-records-remaster-collection/',
    destination: '/news/the-dreamy-records-remaster-collection/',
  },
  {
    source: '/2025/08/25/post-1698/',
    destination: '/news/post-1698/',
  },
  {
    source: '/2025/09/01/post-1716/',
    destination: '/news/post-1716/',
  },
  {
    source: '/2025/10/21/eclipse/',
    destination: '/news/eclipse/',
  },
  {
    source: '/2025/11/26/post-1749/',
    destination: '/news/post-1749/',
  },
  {
    source: '/2025/11/30/post-1755/',
    destination: '/news/post-1755/',
  },
  {
    source: '/2025/12/28/post-1771/',
    destination: '/news/post-1771/',
  },
  {
    source: '/2026/01/01/happy-new-year-2026/',
    destination: '/news/happy-new-year-2026/',
  },
  {
    source: '/2026/03/16/post-1804/',
    destination: '/news/post-1804/',
  },
  {
    source: '/2026/04/25/dream-dance-floor-01/',
    destination: '/news/dream-dance-floor-01/',
  },
  {
    source: '/2026/04/26/post-1819/',
    destination: '/news/post-1819/',
  },
  {
    source: '/2026/08/18/post-1839/',
    destination: '/news/post-1839/',
  },
  {
    source: '/blog/post-1639/',
    destination: '/news/post-1639/',
  },
  {
    source: '/blog/post-1658/',
    destination: '/news/post-1658/',
  },
  {
    source: '/booth/post-200/',
    destination: '/news/post-200/',
  },
  {
    source: '/booth/post-213/',
    destination: '/news/post-213/',
  },
  {
    source: '/booth/post-318/',
    destination: '/news/post-318/',
  },
  {
    source: '/event/post-116/',
    destination: '/news/post-116/',
  },
  {
    source: '/event/post-1539/',
    destination: '/news/post-1539/',
  },
  {
    source: '/event/post-1598/',
    destination: '/news/post-1598/',
  },
  {
    source: '/event/post-185/',
    destination: '/news/post-185/',
  },
  {
    source: '/event/post-268/',
    destination: '/news/post-268/',
  },
  {
    source: '/other/happy-new-year-2026/',
    destination: '/news/happy-new-year-2026/',
  },
  {
    source: '/other/post-135/',
    destination: '/news/post-135/',
  },
  {
    source: '/other/post-148/',
    destination: '/news/post-148/',
  },
  {
    source: '/other/post-1556/',
    destination: '/news/post-1556/',
  },
  {
    source: '/other/post-1606/',
    destination: '/news/post-1606/',
  },
  {
    source: '/other/post-1650/',
    destination: '/news/post-1650/',
  },
  {
    source: '/other/post-1652/',
    destination: '/news/post-1652/',
  },
  {
    source: '/other/post-1698/',
    destination: '/news/post-1698/',
  },
  {
    source: '/other/post-1716/',
    destination: '/news/post-1716/',
  },
  {
    source: '/other/post-1749/',
    destination: '/news/post-1749/',
  },
  {
    source: '/other/post-1755/',
    destination: '/news/post-1755/',
  },
  {
    source: '/other/post-1771/',
    destination: '/news/post-1771/',
  },
  {
    source: '/other/post-1804/',
    destination: '/news/post-1804/',
  },
  {
    source: '/other/post-1819/',
    destination: '/news/post-1819/',
  },
  {
    source: '/other/post-1839/',
    destination: '/news/post-1839/',
  },
  {
    source: '/other/post-326/',
    destination: '/news/post-326/',
  },
  {
    source: '/other/post-54/',
    destination: '/news/post-54/',
  },
  {
    source: '/other/post-63/',
    destination: '/news/post-63/',
  },
  {
    source: '/release/all-dreambreak-remix-phase-1/',
    destination: '/news/all-dreambreak-remix-phase-1/',
  },
  {
    source: '/release/dream-dance-floor-01/',
    destination: '/news/dream-dance-floor-01/',
  },
  {
    source: '/release/eclipse/',
    destination: '/news/eclipse/',
  },
  {
    source: '/release/forever-night/',
    destination: '/news/forever-night/',
  },
  {
    source: '/release/future-magic/',
    destination: '/news/future-magic/',
  },
  {
    source: '/release/planet-world/',
    destination: '/news/planet-world/',
  },
  {
    source: '/release/the-dreamy-records-remaster-collection/',
    destination: '/news/the-dreamy-records-remaster-collection/',
  },
  {
    source: '/website/post-177/',
    destination: '/news/post-177/',
  },
  {
    source: '/website/post-19/',
    destination: '/news/post-19/',
  },
] as const;
